### ISSUE TITLE
esc2text output error

### ISSUE THREAD

**Issue by KlustoR** [receipt-print-hq/escpos-tools#20] opened 2017-05-21 14:07 UTC
Hi,

I'm trying to capture the output send by an Epson tm-t20ii printer and converting that to text.
I am able to capture data with nc (or as i prefer a perl script).
When i try to print that file using "cat tmp.bin > /dev/usb/lp0" i get a correct looking receipt.
But when i try to run it through esc2text i get the following output : 

<details>
  <summary>
Click to expand  
</summary>

pi@raspberrypi:~/pos/tmp $ cat output.txt
WARNING: Unknown command (J
WARNING: Unknown command (J
WARNING: Unknown command (J
WARNING: Unknown command P
WARNING: Unknown command 8
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 0
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 0
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 0
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command `
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 1
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command B
WARNING: Unknown command 
WARNING: Unknown command B
WARNING: Unknown command 
WARNING: Unknown command B
WARNING: Unknown command 
WARNING: Unknown command B
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command B
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command P
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command `
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command ?
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command `
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command  
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 8
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 

WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command ?
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command 
WARNING: Unknown command @
WARNING: Unknown command @
WARNING: Unknown command 
WARNING: Unknown command ?

L?w0p018? @?<@? @???????B@???@??@???L?0|?????? @???@?8p@??????D???B??????|<????????????????????????????????????????????????????????????????????????????????????????????????????????????? ?@@ ? @@@$ ?d? @@@$ ? @@$ ? @B ? @B ? ??  ?? !?  ?@?  @@?  @@?   @@ ?9??????00?????0@?@"B@  ?@AB@   ??B@  ???B?s??x?@ ? ??? ?,A?@@??@??@@@@ ????? @@ ??? @?@ ????@@ ???@???@ ?@ @ ? A @@@ ?@ "????s??????@??@@???????8@@?@@?@@?"@@@?"x@@@???x?@@@?"@??"@@@?"?@@@?"@@@??@@?@@ @@??"x ?????Dx??DDp??}??       ???|?? ???>??????p  ?,A????PcP??@@0???0B`??  ??@@@<0@?  ??@@@?0 ?? B????@@@?? ? B@@@?@ ? $@@@P@ @  $?? 0B@@p@ @ ???B@@?_???~??|?????? ????? @@@?@?@???????<?@????  D"A??   @????  @B??q???????? @BD???? ?@@BD??????@?D???0 @A(????00 ~(????0???@???0@@???   @ p?  @??A??` @ ? `0?`@???????>???? ???? ?????????@?@?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????>???????? @C?0@ @?? @B????@ @@? @B??B@ @@? @D?B@ @@BD? ?@ @@BD? P@ @?~(?  ?@ B(?   @ @?B   @ @B?@  @ @B?@   @ @B???   @ @B?A 8 0?@@?????σ?>??/???> ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????@???>??????????????8 ? A?  A@@ ?@@ ???    @?@@ @@??  @?    @?@@  @@@?  @?   @?@@  @@@ ?   @?@@  @@@ ?  @?@@  @@@ ??????A@  @@@ ???@  ~@  @@@" ?   B@  @@@?  !@??   A@?  @@?  !@??@   @?@@ @@?@@  ????@   @?@@?   ?  A???p@  @@@????>?????_?????p????@??|??>??????????}??????  ??A ?? ? ? @?@????   @@? ??@????    @@!? ???    @@"? ??@? ?@
                                                     ?  @@$? `P@E ? ?@  @@(?  ?@E <??  @@6?  @I ?? ??  @@!? ? @I  ?  @@ ?? ? H??  @@ @?A? P? ? @@? @?A? P? ?@? ?  ??? P?? ?@??8??~????? @????????????@?????>???|??????????????? `  A??@? ?  ??  @? @@?  ???  @?!  @@ ? @?!  @@!B0 @? @  @@!B0@? @   @@"??? @@  @@?0?@@? @?  @@?0 @? @  @@  ?
 @? @  @@ !?
@ @? @ @@? !?@ @? ? ? ` !??p@@?? ?????~??~????_???????????

L,90p018???????????????????????????????????????????????????????????????????????????????????????????????????8|??>@ ??? ? ? @@@ ?  @@?????? ?  @@
`?? ?  @@?@ ?  @@ @ ?  @ ?? ?  @ `@ ?  @ ?@??  @ ?@ ? @@????@ ??0A@?? ???9????>p??>??????|  ??@0@@@?G?  ? H@ @!P@?
??!` 0 !` @ ?` @  ?  @`@@? @ ?? ??9??|????????????????????????????????????????????????????????????????????????????????????????????????????|????>@  ???  @  ???? @0@?  G??  ?H@?    !P@? ?? !` ? 0 !` ? @ ?` ? @   ?@`?@ ? @0 ??? 0???8??>????????|? ??? ? @  ?|  0@?  @  @   @@??  @0  @@  @@  @@@`???  ???????8??|?|??????|?   `?? ?   ?   ??> @@@A?  G?@@?? ?H@@A@  !P@@A@? !` @A??!` @A?`  A   @?@? ? @ `!?@?? 0??p?|???
</details>

 
The file in question, comes from a working windows POS, setup using correct epson drivers.
When i compare the file to the receipt-with-logo.bin demo file, they seem to be totally different. 
Making me think i need to convert this more before running it through esc2text ?
Any idea's ?

[tmp.bin.zip](https://github.com/receipt-print-hq/escpos-tools/files/1017040/tmp.bin.zip)

**Comment by mike42** [comment] 2017-05-22 07:06
This is quite an interesting test file, thanks for posting it. It definitely shows some buggy behaviour.

I'll work a bit with this file and get back to you. It looks like it's mostly raster data, which we can't extract yet, but I can certainly make some improvements based on what you've posted here.

**Comment by AlphaWarrioR** [comment] 2017-05-22 08:51
So perhaps the printer driver is rastering it.
Is this known behavior for Epson printers ?
I will try using generic text driver in an hour and update.

Op 22 mei 2017 om 09:06 heeft Michael Billington <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


This is quite an interesting test file, thanks for posting it. It definitely shows some buggy behaviour.

I'll work a bit with this file and get back to you. It looks like it's mostly raster data, which we can't extract yet, but I can certainly make some improvements based on what you've posted here.

**Comment by KlustoR** [comment] 2017-05-22 11:47
I seem to pretty much the same output get using generic text driver

**Comment by mike42** [comment] 2017-05-22 11:56
Working on this in a branch called 'bugfix/unrecognised-commands', should be more like this-

```
[DEBUG] SelectPeripheralDeviceCmd 
[DEBUG] UnknownDataCmd 
[DEBUG] UnknownDataCmd 
[DEBUG] UnknownDataCmd 
[DEBUG] UnknownCommandOneArg 
[DEBUG] UnknownCommandOneArg 
[DEBUG] SelectPaperEndSensorsCmd 
[DEBUG] SelectDefaultLineSpacingCmd 
[DEBUG] SelectInternationalCharacterSetCmd 
[DEBUG] SelectCodeTableCmd 
[DEBUG] EnableSmoothingCmd 
[DEBUG] CommandTwoArgs 
[DEBUG] PrintAndFeedCmd (LineBreak)

[DEBUG] PrintAndFeedCmd (LineBreak)

[DEBUG] SetAbsolutePrintPosCmd 
[DEBUG] GraphicsLargeDataCmd 
[DEBUG] GraphicsDataCmd 
[DEBUG] PrintAndFeedCmd (LineBreak)

[DEBUG] PrintAndFeedCmd (LineBreak)

[DEBUG] PrintAndFeedCmd (LineBreak)

[DEBUG] SetAbsolutePrintPosCmd 
[DEBUG] GraphicsLargeDataCmd 
[DEBUG] GraphicsDataCmd 
[DEBUG] PrintAndFeedCmd (LineBreak)

[DEBUG] FeedAndCutCmd 
```

The receipt is certainly wrapped up as raster images, so you can't retrieve the content with this parser yet. Unpacking the content in those`GraphicsLargeDataCmd` calls (responsible for all the gibberish before) will happen as part of issue #6.

**Comment by KlustoR** [comment] 2017-05-22 12:03
Do you know of any POS printer driver that doesn't do this ? I can always try use another driver, and see if the Epson wings it

**Comment by mike42** [comment] 2017-05-26 13:42
I directly generate the receipts using [mike42/escpos-php](https://github.com/mike42/escpos-php) library, then use raw printing to deliver the data.

I think the issue you were having is solved in the latest `master` branch. Can you please try running your test file through the tools again to verify? You might just need to activate the `imagick` extension if you don't have it yet.

Expect text file to be created with some whitespace only, and a list of commands on the terminal:

```
php escimages tmp.bin > tmp.txt
```

Expect two images of parts of the receipt to be written in `pbm` format, with a copy of each in `png` format as well-

```bash
php esc2text.php tmp.bin -v
```

Expect HTML file to be written-

```bash
php esc2html.php tmp.bin > tmp.html
```

This output should appear visually similar to the actual receipt:

![screenshot from 2017-05-26 23-18-20](https://cloud.githubusercontent.com/assets/2080552/26496912/c39f2382-426c-11e7-81ac-b1a50ad72e66.png)

**Comment by KlustoR** [comment] 2017-05-27 00:07
I've tried it now and have gotten the images.
Now is there any way we can go about extracting the text from those images without running each file through tesseract ?

**Comment by mike42** [comment] 2017-05-27 12:54
Yes, to extract text from images, you will need an OCR tool, since there's no extra data we can recover from the ESC/POS. If you need perfect output, you will need to train tesseract for the font being used.

It sounds like you are familiar with it, but for future readers, I'll point out that the PBM files can be scooped up in alphabetical order and OCR'ed directly, no need to waste CPU cycles with PNG compression or TIFF conversion.

```bash
# tesseract
sudo apt-get install tesseract-ocr imagemagick
rm *.pbm
php escimages.php input_files/tmp.bin
convert -append *.pbm pbm:- | tesseract - -
cat out.txt
```

Also, am I able to include this sample file in the repository, under the MIT license, for regression testing purposes?

Note: Tried `pdfsandwich` as a second option, was slow and the output was poor quality.

```bash
# pdfsandwich
sudo apt-get install pdfsandwich wkhtmltopdf
php esc2html.php input_files/tmp.bin > tmp.html
wkhtmltopdf --page-size A7 tmp.html tmp.pdf
pdfsandwich tmp.pdf 
pdftotext -layout tmp_ocr.pdf 
cat tmp_ocr.txt
```

**Comment by mike42** [comment] 2017-06-25 06:26
Closing this off, I believe this bug has now been resolved.

**Closed by mike42** 2017-06-25 06:26 UTC
Labels: bug

**Comment by KlustoR** [comment] 2017-06-25 15:32
I'm sorry for the late reply, i was busy on another task.
Yes you can include the sample file, no problem.
This issue is resolved yes, thanks 👍 💯

**Comment by nsatech** [comment] 2017-08-21 06:11
[test.zip](https://github.com/receipt-print-hq/escpos-tools/files/1237918/test.zip)

Sorry to jump in here, but I am having the same problem with my test file.

When I do php escpos2text.php test.bin, I get the following output:

...
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command GS
WARNING: Unknown command DLE NUL
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command FS
WARNING: Unknown command ESC W
PuTTYWARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
...

When I use: php escimages test.bin > test.txt, I get:

Could not open input file: escimages


----

The receipt is generated with the Seiko CAPD347 Driver, so the ESC/POS format should be correct ... but it looks different to the example provided.

**Comment by zarafati** [comment] 2019-10-09 17:04
@mike42  I used: php esc2html.php ascii.bin > output.html
and i get a blank page with any text.
so what's the problem?
this is my file:
[ascii.txt](https://github.com/receipt-print-hq/escpos-tools/files/3708562/ascii.txt)
